
import { WeaponSchema } from '../../types';

export const TIER_3_UNITS: WeaponSchema[] = [
  // --- BULLET ---
  { id: 'triple_shot', name: 'Triple Shot', description: 'Wide spread.', tier: 30, type: 'Bullet', barrels: [{offset:0,width:20,length:45,angle:0,delay:0},{offset:0,width:20,length:42,angle:0.5,delay:0},{offset:0,width:20,length:42,angle:-0.5,delay:0}], stats: {damage:15,reload:30,range:60,speed:6,spread:0.05,recoil:4,bulletSize:9,bulletCount:1}, skill: {type:'FOCUS',name:'Converge',cooldown:600,duration:120} },
  { id: 'quad_tank', name: 'Quad Tank', description: '4-Way fire.', tier: 30, type: 'Bullet', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a=>({offset:0,width:20,length:42,angle:a,delay:0})), stats: {damage:18,reload:25,range:55,speed:6,spread:0.05,recoil:1,bulletSize:9,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Reflect',cooldown:700,duration:150} },
  { id: 'twin_flank', name: 'Twin Flank', description: 'Double ends.', tier: 30, type: 'Bullet', barrels: [{offset:5,width:18,length:42,angle:0,delay:0},{offset:-5,width:18,length:42,angle:0,delay:10},{offset:5,width:18,length:42,angle:Math.PI,delay:0},{offset:-5,width:18,length:42,angle:Math.PI,delay:10}], stats: {damage:14,reload:18,range:60,speed:6,spread:0.05,recoil:2,bulletSize:9,bulletCount:1}, skill: {type:'BARRAGE',name:'Overload',cooldown:600,duration:60} },
  { id: 'auto_3', name: 'Auto-3', description: '3 Auto Turrets.', tier: 30, type: 'Bullet', barrels: [0, 2*Math.PI/3, 4*Math.PI/3].map(a=>({offset:0,width:16,length:28,angle:a,delay:0,type:'Auto' as const})), stats: {damage:10,reload:20,range:60,speed:8,spread:0.05,recoil:0,bulletSize:7,bulletCount:1}, skill: {type:'CHRONO_FIELD',name:'Stasis',cooldown:1200,duration:180} },
  { id: 'tri_angle', name: 'Tri-Angle', description: 'Speedster.', tier: 30, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:22,length:50,angle:0,delay:0},{offset:0,width:20,length:38,angle:2.6,delay:0},{offset:0,width:20,length:38,angle:-2.6,delay:0}], stats: {damage:15,reload:15,range:50,speed:7,spread:0.1,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'OVERCLOCK',name:'Overdrive',cooldown:300,duration:60} },
  
  // --- HEAVY ---
  { id: 'destroyer', name: 'Destroyer', description: 'Massive shot.', tier: 30, type: 'Bullet', barrels: [{offset:0,width:60,length:65,angle:0,delay:0},{offset:0,width:64,length:30,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:120,reload:90,range:80,speed:5,spread:0,recoil:25,bulletSize:9.8,bulletCount:1}, skill: {type:'ROCKET_JUMP',name:'Blast Jump',cooldown:400,duration:20} },
  { id: 'gunner', name: 'Gunner', description: 'Fast fire.', tier: 30, type: 'Bullet', barrels: [{offset:8,width:10,length:45,angle:0,delay:0},{offset:-8,width:10,length:45,angle:0,delay:5},{offset:16,width:10,length:40,angle:0,delay:10},{offset:-16,width:10,length:40,angle:0,delay:15}], stats: {damage:8,reload:6,range:50,speed:8,spread:0.1,recoil:2,bulletSize:7,bulletCount:1}, skill: {type:'FOCUS',name:'Laser Beam',cooldown:600,duration:150} },
  
  // --- SNIPER ---
  { id: 'assassin', name: 'Assassin', description: 'Deep vision.', tier: 30, type: 'Bullet', barrels: [{offset:0,width:26,length:95,angle:0,delay:0},{offset:0,width:30,length:40,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:60,reload:60,range:150,speed:14,spread:0,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'PHANTOM_STEP',name:'Phantom',cooldown:1200,duration:200} },
  { id: 'hunter', name: 'Hunter', description: 'Shotgun-Sniper.', tier: 30, type: 'Bullet', barrels: [{offset:0,width:28,length:70,angle:0,delay:5},{offset:0,width:20,length:85,angle:0,delay:0}], stats: {damage:35,reload:50,range:100,speed:10,spread:0.01,recoil:5,bulletSize:10,bulletCount:1}, skill: {type:'STEALTH',name:'Veil',cooldown:900,duration:300} },
  { id: 'stalker_proto', name: 'Rogue', description: 'Semi-invisible.', tier: 30, type: 'Bullet', bodyType: 'Trapezoid', barrels: [{offset:0,width:24,length:65,angle:0,delay:0}], stats: {damage:40,reload:40,range:110,speed:12,spread:0,recoil:4,bulletSize:8,bulletCount:1}, skill: {type:'STEALTH',name:'Cloak',cooldown:600,duration:300} },

  // --- SPECIALIST ---
  { id: 'blaster', name: 'Blaster', description: 'Shotgun.', tier: 30, type: 'Shotgun', barrels: [{offset:0,width:35,length:60,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:28,length:65,angle:0,delay:0},{offset:15,width:8,length:50,angle:0,delay:0},{offset:-15,width:8,length:50,angle:0,delay:0}], stats: {damage:12,reload:50,range:55,speed:8,spread:0.3,recoil:15,bulletSize:6,bulletCount:5}, skill: {type:'DASH',name:'Slide',cooldown:300,duration:15} },
  { id: 'grenadier', name: 'Grenadier', description: 'Explosives.', tier: 30, type: 'Launcher', barrels: [{offset:0,width:40,length:50,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:45,angle:0,delay:0}], stats: {damage:60,reload:60,range:120,speed:4,spread:0.05,recoil:10,bulletSize:10,bulletCount:1}, skill: {type:'BARRAGE',name:'Rapid Launch',cooldown:600,duration:60} },
  { id: 'rocketeer_proto', name: 'Rocket Hull', description: 'Rear boost.', tier: 30, type: 'Launcher', barrels: [{offset:0,width:30,length:60,angle:0,delay:0},{offset:0,width:30,length:40,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:50,reload:45,range:130,speed:5,spread:0,recoil:5,bulletSize:10,bulletCount:1}, skill: {type:'ROCKET_JUMP',name:'Boost',cooldown:400,duration:20} },

  // --- DRONE / SUPPORT ---
  { id: 'overseer', name: 'Overseer', description: 'Drones.', tier: 30, type: 'Drone', barrels: [{offset:0,width:34,length:45,angle:Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:0,width:34,length:45,angle:-Math.PI/2,delay:0,type:'Trapezoid' as const}], stats: {damage:25,reload:100,range:0,speed:0,spread:0,recoil:0,bulletSize:10,bulletCount:2}, skill: {type:'REPEL',name:'Repel',cooldown:120,duration:60} },
  { id: 'cruiser', name: 'Cruiser', description: 'Swarm.', tier: 30, type: 'Swarm', barrels: [{offset:0,width:40,length:45,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:5,reload:30,range:60,speed:0,spread:0.5,recoil:0,bulletSize:5,bulletCount:6}, skill: {type:'MAGNET',name:'Gather',cooldown:600,duration:180} },
  { id: 'tri_trapper', name: 'Tri-Trapper', description: '3 Traps.', tier: 30, type: 'Trap', barrels: [0, 2*Math.PI/3, 4*Math.PI/3].map(a=>({offset:0,width:38,length:40,angle:a,delay:0,type:'Trapezoid' as const})), stats: {damage:35,reload:45,range:180,speed:4,spread:0,recoil:0,bulletSize:14,bulletCount:1}, skill: {type:'FORTIFY',name:'Bunker',cooldown:900,duration:180} },
  { id: 'auto_trapper', name: 'Auto Trapper', description: 'Trap + Auto.', tier: 30, type: 'Trap', barrels: [{offset:0,width:40,length:45,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:16,length:24,angle:0,delay:0,type:'Auto' as const}], stats: {damage:30,reload:50,range:150,speed:4,spread:0,recoil:0,bulletSize:14,bulletCount:1}, skill: {type:'FORTIFY',name:'Sentry',cooldown:900,duration:180} },
  { id: 'builder', name: 'Builder', description: 'Fortify.', tier: 30, type: 'Builder', bodyType: 'Square', barrels: [{offset:0,width:34,length:50,angle:0,delay:0,type:'Construct' as const}], stats: {damage:15,reload:50,range:120,speed:4,spread:0,recoil:10,bulletSize:14,bulletCount:1}, skill: {type:'CONSTRUCT_WALL',name:'Wall',cooldown:900,duration:180} },

  // --- NEW ARCHETYPES (Tier 3 Expansion) ---
  { id: 'ricochet', name: 'Ricochet', description: 'Bouncy.', tier: 30, type: 'Bullet', bodyType: 'Diamond', barrels: [{offset:0,width:20,length:55,angle:0,delay:0},{offset:12,width:8,length:45,angle:0,delay:0}], stats: {damage:18,reload:20,range:90,speed:8,spread:0.02,recoil:3,bulletSize:8,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Angle Cal',cooldown:600,duration:120} },
  { id: 'cleric', name: 'Cleric', description: 'Healer.', tier: 30, type: 'Healer', bodyType: 'Cross', barrels: [{offset:8,width:18,length:45,angle:0,delay:0,type:'Injector' as const},{offset:-8,width:18,length:45,angle:0,delay:5,type:'Injector' as const}], stats: {damage:6,reload:15,range:90,speed:9,spread:0.1,recoil:2,bulletSize:8,bulletCount:1}, effect: 'HEAL', skill: {type:'SHIELD',name:'Aegis',cooldown:600,duration:120} },
  { id: 'spitfire', name: 'Spitfire', description: 'Flamethrower.', tier: 30, type: 'Flamethrower', barrels: [{offset:0,width:30,length:55,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:6,reload:3,range:45,speed:9,spread:0.2,recoil:1,bulletSize:10,bulletCount:1}, effect: 'BURN', skill: {type:'DASH',name:'Dash',cooldown:300,duration:25} },
  { id: 'phaser', name: 'Phaser', description: 'Laser.', tier: 30, type: 'Laser', barrels: [{offset:0,width:20,length:85,angle:0,delay:0},{offset:0,width:24,length:30,angle:0,delay:0,type:'Auto' as const}], stats: {damage:35,reload:40,range:140,speed:20,spread:0,recoil:5,bulletSize:6,bulletCount:1}, skill: {type:'TELEPORT',name:'Phase',cooldown:400,duration:10} },
  { id: 'smasher', name: 'Smasher', description: 'Ram.', tier: 30, type: 'Ram', bodyType: 'Hexagon', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'BERSERK',name:'Adrenaline',cooldown:600,duration:180} },
  { id: 'infector', name: 'Infector', description: 'Corrosive.', tier: 30, type: 'Trap', barrels: [{offset:0,width:28,length:45,angle:0,delay:0,type:'Injector' as const}], stats: {damage:8,reload:15,range:80,speed:5,spread:0.3,recoil:2,bulletSize:8,bulletCount:1}, effect: 'CORROSION', skill: {type:'EMP',name:'Miasma',cooldown:900,duration:180} },
  { id: 'attractor', name: 'Attractor', description: 'Pull.', tier: 30, type: 'Ram', bodyType: 'Crescent', barrels: [], stats: {damage:2,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'MAGNET',name:'Magnetize',cooldown:300,duration:60} },
  { id: 'void_walker', name: 'Void Walker', description: 'Blink.', tier: 30, type: 'Bullet', bodyType: 'Diamond', barrels: [{offset:0,width:18,length:50,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:25,reload:45,range:100,speed:10,spread:0,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'TELEPORT',name:'Blink',cooldown:200,duration:10} },
  { id: 'cryo', name: 'Cryo', description: 'Slow.', tier: 30, type: 'Flamethrower', barrels: [{offset:0,width:32,length:50,angle:0,delay:0,type:'Construct' as const}], stats: {damage:5,reload:4,range:50,speed:8,spread:0.15,recoil:2,bulletSize:9,bulletCount:1}, effect: 'FREEZE', skill: {type:'CHRONO_FIELD',name:'Flash Freeze',cooldown:900,duration:120} },
  { id: 'volt', name: 'Volt', description: 'Lightning.', tier: 30, type: 'Tesla', barrels: [{offset:0,width:24,length:55,angle:0,delay:0}], stats: {damage:3,reload:10,range:250,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:1}, effect: 'SHOCK', skill: {type:'EMP',name:'Discharge',cooldown:600,duration:30} },
  { id: 'prism', name: 'Prism', description: 'Refract.', tier: 30, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:20,length:45,angle:0,delay:0},{offset:15,width:10,length:35,angle:0,delay:0},{offset:-15,width:10,length:35,angle:0,delay:0}], stats: {damage:10,reload:25,range:70,speed:8,spread:0.1,recoil:3,bulletSize:7,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Refract',cooldown:600,duration:120} },
  { id: 'sonic_blaster', name: 'Screamer', description: 'Sonic wave.', tier: 30, type: 'Sonic', barrels: [{offset:0,width:45,length:45,angle:0,delay:0,type:'Dish' as const}], stats: {damage:15,reload:40,range:100,speed:6,spread:0,recoil:5,bulletSize:15,bulletCount:1}, skill: {type:'EMP',name:'Shout',cooldown:500,duration:30} },
  { id: 'auto_smasher', name: 'Auto Smash', description: 'Auto Turret Ram.', tier: 30, type: 'Ram', bodyType: 'Hexagon', barrels: [{offset:0,width:16,length:24,angle:0,delay:0,type:'Auto' as const}], stats: {damage:5,reload:20,range:50,speed:0,spread:0,recoil:0,bulletSize:6,bulletCount:1}, skill: {type:'BERSERK',name:'Rampage',cooldown:600,duration:120} },
  { id: 'hive_proto', name: 'Hive', description: 'Trap spawner.', tier: 30, type: 'Trap', barrels: [{offset:0,width:30,length:40,angle:0,delay:0,type:'Trapezoid' as const},{offset:20,width:10,length:30,angle:0.5,delay:0},{offset:-20,width:10,length:30,angle:-0.5,delay:0}], stats: {damage:10,reload:20,range:80,speed:5,spread:0.2,recoil:2,bulletSize:8,bulletCount:1}, skill: {type:'RECALL',name:'Swarm',cooldown:800,duration:60} }
];
