
import { WeaponSchema } from '../../types';

export const TIER_5_UNITS: WeaponSchema[] = [
  // --- BULLET GODS ---
  { id: 'streamliner', name: 'Streamliner', description: '5 Inline.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:22,length:80,angle:0,delay:0},{offset:0,width:22,length:70,angle:0,delay:3},{offset:0,width:22,length:60,angle:0,delay:6},{offset:0,width:22,length:50,angle:0,delay:9},{offset:0,width:22,length:40,angle:0,delay:12}], stats: {damage:8,reload:15,range:80,speed:8,spread:0.05,recoil:1,bulletSize:7,bulletCount:1}, skill: {type:'FOCUS',name:'Laser Sight',cooldown:400,duration:120} },
  { id: 'sprayer', name: 'Sprayer', description: 'Machine gun.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:32,length:60,angle:0,delay:0},{offset:0,width:20,length:70,angle:0,delay:2,type:'Trapezoid' as const}], stats: {damage:10,reload:5,range:60,speed:8,spread:0.3,recoil:3,bulletSize:8,bulletCount:1}, skill: {type:'BARRAGE',name:'Lead Hose',cooldown:600,duration:90} },
  { id: 'cyclone', name: 'Cyclone', description: '12 Barrel.', tier: 60, type: 'Bullet', barrels: Array.from({length:12},(_,i)=>({offset:0,width:18,length:45,angle:i*Math.PI*2/12,delay:i*2})), stats: {damage:12,reload:4,range:60,speed:7,spread:0.1,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Eye of Storm',cooldown:600,duration:180} },
  { id: 'auto_gunner', name: 'Auto Gunner', description: 'Gunner + Auto.', tier: 60, type: 'Bullet', barrels: [{offset:8,width:10,length:45,angle:0,delay:0},{offset:-8,width:10,length:45,angle:0,delay:5},{offset:16,width:10,length:40,angle:0,delay:10},{offset:-16,width:10,length:40,angle:0,delay:15},{offset:0,width:16,length:24,angle:0,delay:0,type:'Auto' as const}], stats: {damage:9,reload:5,range:50,speed:8,spread:0.1,recoil:2,bulletSize:7,bulletCount:1}, skill: {type:'FOCUS',name:'Target Lock',cooldown:400,duration:90} },
  { id: 'gatling', name: 'Gatling', description: 'Rotary.', tier: 60, type: 'Bullet', barrels: [{offset:15,width:18,length:55,angle:0,delay:0},{offset:-15,width:18,length:55,angle:0,delay:3},{offset:0,width:20,length:60,angle:0,delay:6}], stats: {damage:11,reload:3,range:65,speed:9,spread:0.2,recoil:5,bulletSize:8,bulletCount:1}, skill: {type:'OVERCLOCK',name:'Spin Up',cooldown:500,duration:120} },
  { id: 'sniper_guard', name: 'Sniper Guard', description: 'Rear Sniper.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:26,length:85,angle:0,delay:0},{offset:0,width:26,length:85,angle:Math.PI,delay:0}], stats: {damage:60,reload:60,range:150,speed:14,spread:0,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'STEALTH',name:'Double Blind',cooldown:1000,duration:300} },

  // --- HEAVY HITTERS ---
  { id: 'annihilator', name: 'Annihilator', description: 'Huge bullet.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:90,length:70,angle:0,delay:0}], stats: {damage:180,reload:100,range:70,speed:5,spread:0,recoil:40,bulletSize:10,bulletCount:1}, skill: {type:'ROCKET_JUMP',name:'Meteor Dash',cooldown:400,duration:20} },
  { id: 'hybrid', name: 'Hybrid', description: 'Destroyer + Drones.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:60,length:65,angle:0,delay:0},{offset:0,width:20,length:30,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:120,reload:90,range:80,speed:5,spread:0,recoil:25,bulletSize:9.8,bulletCount:2}, skill: {type:'REPEL',name:'Rear Guard',cooldown:300,duration:60} },
  { id: 'auto_destroyer', name: 'Auto Destroyer', description: 'Heavy + Auto.', tier: 60, type: 'Bullet', barrels: [{offset:0,width:60,length:65,angle:0,delay:0},{offset:0,width:20,length:30,angle:0,delay:0,type:'Auto' as const}], stats: {damage:120,reload:90,range:80,speed:5,spread:0,recoil:25,bulletSize:9.8,bulletCount:1}, skill: {type:'SHIELD',name:'Heavy Plate',cooldown:600,duration:120} },

  // --- SHOTGUNS ---
  { id: 'vanquisher', name: 'Vanquisher', description: 'Heavy burst.', tier: 60, type: 'Shotgun', barrels: [{offset:0,width:45,length:50,angle:0,delay:0,type:'Construct' as const},{offset:0,width:38,length:65,angle:0,delay:0},{offset:0,width:40,length:15,angle:0,delay:0,type:'Trapezoid' as const},{offset:22,width:12,length:45,angle:0,delay:0},{offset:-22,width:12,length:45,angle:0,delay:0}], stats: {damage:14,reload:40,range:70,speed:10,spread:0.25,recoil:25,bulletSize:7,bulletCount:8}, skill: {type:'DASH',name:'Breach',cooldown:350,duration:20} },
  { id: 'shotgun_mk2', name: 'Shotgun MK2', description: 'More pellets.', tier: 60, type: 'Shotgun', barrels: [{offset:0,width:45,length:65,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:35,length:70,angle:0,delay:0}], stats: {damage:12,reload:55,range:65,speed:9,spread:0.35,recoil:20,bulletSize:6,bulletCount:10}, skill: {type:'BERSERK',name:'Rapid Fire',cooldown:500,duration:80} },
  { id: 'triple_blaster', name: 'Tri-Blaster', description: '3-Way Shotgun.', tier: 60, type: 'Shotgun', barrels: [{offset:0,width:30,length:50,angle:0,delay:0},{offset:0,width:30,length:50,angle:Math.PI/2,delay:0},{offset:0,width:30,length:50,angle:-Math.PI/2,delay:0}], stats: {damage:10,reload:45,range:50,speed:8,spread:0.25,recoil:10,bulletSize:6,bulletCount:4}, skill: {type:'BARRAGE',name:'Crowd Control',cooldown:600,duration:60} },

  // --- ROCKETS ---
  { id: 'cruise_launcher', name: 'Cruise', description: 'Tracking.', tier: 60, type: 'Launcher', barrels: [{offset:18,width:28,length:60,angle:0,delay:0,type:'Trapezoid' as const},{offset:-18,width:28,length:60,angle:0,delay:20,type:'Trapezoid' as const},{offset:0,width:20,length:40,angle:0,delay:0}], stats: {damage:70,reload:35,range:150,speed:5,spread:0.1,recoil:5,bulletSize:11,bulletCount:1}, skill: {type:'FOCUS',name:'Lock',cooldown:400,duration:150} },
  { id: 'missile_silo', name: 'Missile Silo', description: 'Vertical launch.', tier: 60, type: 'Launcher', bodyType: 'Square', barrels: [{offset:0,width:60,length:30,angle:0,delay:0,type:'Construct' as const},{offset:0,width:50,length:20,angle:0,delay:0}], stats: {damage:120,reload:100,range:300,speed:3,spread:0,recoil:20,bulletSize:15,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Nuke',cooldown:900,duration:60} },
  { id: 'torpedo', name: 'Torpedo', description: 'Slow deadly.', tier: 60, type: 'Launcher', barrels: [{offset:0,width:50,length:80,angle:0,delay:0}], stats: {damage:150,reload:120,range:250,speed:4,spread:0,recoil:30,bulletSize:14,bulletCount:1}, skill: {type:'STEALTH',name:'Submerge',cooldown:900,duration:300} },

  // --- DRONE / SWARM ---
  { id: 'battleship', name: 'Battleship', description: 'Tiny swarm.', tier: 60, type: 'Swarm', barrels: [{offset:12,width:14,length:40,angle:Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:-12,width:14,length:40,angle:Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:12,width:14,length:40,angle:-Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:-12,width:14,length:40,angle:-Math.PI/2,delay:0,type:'Trapezoid' as const}], stats: {damage:4,reload:10,range:70,speed:0,spread:0.5,recoil:0,bulletSize:4,bulletCount:30}, skill: {type:'REPEL',name:'Control',cooldown:300,duration:60} },
  { id: 'mother_drone', name: 'Broodmother', description: 'Spawns Carriers.', tier: 60, type: 'Swarm', barrels: [{offset:0,width:60,length:70,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:8,reload:100,range:90,speed:0,spread:0.5,recoil:0,bulletSize:6,bulletCount:4}, skill: {type:'RECALL',name:'Nest',cooldown:600,duration:120} },
  { id: 'necro_trapper', name: 'Necro Trapper', description: 'Square Trap.', tier: 60, type: 'Trap', barrels: [{offset:0,width:45,length:45,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:40,length:30,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:20,reload:30,range:100,speed:4,spread:0,recoil:0,bulletSize:12,bulletCount:10}, skill: {type:'REPEL',name:'Trap Swarm',cooldown:600,duration:120} },

  // --- RAMMERS ---
  { id: 'spike', name: 'Spike', description: 'Max damage.', tier: 60, type: 'Ram', bodyType: 'Spike', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'BERSERK',name:'Impale',cooldown:600,duration:200} },
  { id: 'shredder', name: 'Shredder', description: 'Spinning blades.', tier: 60, type: 'Ram', bodyType: 'Saw', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'GRAVITY_WELL',name:'Vortex Blade',cooldown:900,duration:180} },
  { id: 'star_ram', name: 'Morning Star', description: 'Star Ram.', tier: 60, type: 'Ram', bodyType: 'Star', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'EMP',name:'Radiance',cooldown:600,duration:60} },
  
  // NEW UNIT: BEHEMOTH (Bulldozer Upgrade)
  { 
    id: 'behemoth', name: 'Behemoth', description: 'Massive plow.', tier: 60, type: 'Ram', bodyType: 'Trapezoid', 
    barrels: [{offset: 35, width: 26, length: 50, angle: Math.PI, delay: 0}, {offset: -35, width: 26, length: 50, angle: Math.PI, delay: 0}, {offset: 15, width: 18, length: 40, angle: Math.PI, delay: 5}, {offset: -15, width: 18, length: 40, angle: Math.PI, delay: 5}], 
    stats: {damage: 10, reload: 3, range: 45, speed: 5, spread: 0.1, recoil: 30, bulletSize: 12, bulletCount: 1}, skill: {type: 'SHIELD', name: 'Titan Hull', cooldown: 900, duration: 300} 
  },
  // NEW UNIT: MEAT GRINDER (Buzzsaw Upgrade)
  {
    id: 'shredder_max', name: 'Meat Grinder', description: 'Dual blades.', tier: 60, type: 'Ram', bodyType: 'Saw',
    barrels: [{offset: 0, width: 10, length: 10, angle: 0, delay: 0, type: 'Trapezoid' as const}, {offset: 0, width: 10, length: 10, angle: Math.PI/2, delay: 0, type: 'Trapezoid' as const}, {offset: 0, width: 10, length: 10, angle: Math.PI, delay: 0, type: 'Trapezoid' as const}, {offset: 0, width: 10, length: 10, angle: -Math.PI/2, delay: 0, type: 'Trapezoid' as const}], // Visual mounts
    stats: {damage: 15, reload: 5, range: 100, speed: 7, spread: 0.5, recoil: 0, bulletSize: 6, bulletCount: 8}, // Spews shrapnel
    skill: {type: 'BERSERK', name: 'Grind', cooldown: 450, duration: 120}
  },
  // NEW UNIT: IRON MAIDEN (Briar Upgrade)
  {
    id: 'iron_maiden', name: 'Iron Maiden', description: 'Spiked Fortress.', tier: 60, type: 'Ram', bodyType: 'Spike',
    barrels: Array.from({length: 16}, (_, i) => ({offset: 0, width: 8, length: 45, angle: i * Math.PI / 8, delay: 0, type: 'Spike' as const})),
    stats: {damage: 12, reload: 0, range: 0, speed: 4, spread: 0, recoil: 0, bulletSize: 0, bulletCount: 0},
    skill: {type: 'NANO_ARMOR', name: 'Iron Skin', cooldown: 900, duration: 300}
  },

  // --- SPECIALIST ---
  { id: 'architect_v2', name: 'Citadel', description: 'Permanent base.', tier: 60, type: 'Builder', bodyType: 'Square', barrels: [{offset:0,width:50,length:65,angle:0,delay:0,type:'Construct' as const},{offset:28,width:18,length:30,angle:Math.PI/2,delay:0,type:'Auto' as const},{offset:-28,width:18,length:30,angle:-Math.PI/2,delay:0,type:'Auto' as const}], stats: {damage:30,reload:70,range:200,speed:5,spread:0,recoil:20,bulletSize:22,bulletCount:1}, skill: {type:'CONSTRUCT_WALL',name:'Fortress',cooldown:1800,duration:999} },
  { id: 'railgun', name: 'Railgun', description: 'Hyper-velocity.', tier: 60, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:22,length:120,angle:0,delay:0},{offset:0,width:45,length:75,angle:0,delay:0},{offset:0,width:12,length:35,angle:Math.PI,delay:0}], stats: {damage:150,reload:120,range:300,speed:35,spread:0,recoil:40,bulletSize:8,bulletCount:1}, skill: {type:'ORBITAL_BEAM',name:'Overcharge',cooldown:900,duration:60} },
  { id: 'spectre_v2', name: 'Wraith', description: 'Phase Assassin.', tier: 60, type: 'Bullet', bodyType: 'Crescent', barrels: [{offset:0,width:28,length:85,angle:0,delay:0},{offset:14,width:12,length:65,angle:0,delay:5},{offset:-14,width:12,length:65,angle:0,delay:5}], stats: {damage:90,reload:45,range:160,speed:18,spread:0,recoil:12,bulletSize:8,bulletCount:1}, skill: {type:'PHANTOM_STEP',name:'Void Walk',cooldown:600,duration:120} },
  { id: 'phoenix', name: 'Phoenix', description: 'Fire Rebirth.', tier: 60, type: 'Flamethrower', barrels: [{offset:0,width:40,length:65,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:55,angle:0.5,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:55,angle:-0.5,delay:0,type:'Trapezoid' as const}], stats: {damage:10,reload:2,range:65,speed:11,spread:0.4,recoil:4,bulletSize:16,bulletCount:1}, effect: 'BURN', skill: {type:'TELEPORT',name:'Rebirth',cooldown:900,duration:10} },
  { id: 'absolute_zero', name: 'Absolute Zero', description: 'Blizzard.', tier: 60, type: 'Flamethrower', barrels: [{offset:0,width:45,length:70,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:60,angle:0.3,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:60,angle:-0.3,delay:0,type:'Trapezoid' as const}], stats: {damage:7,reload:1,range:60,speed:9,spread:0.5,recoil:3,bulletSize:14,bulletCount:1}, effect: 'FREEZE', skill: {type:'CHRONO_FIELD',name:'Freeze',cooldown:800,duration:60} },
  { id: 'thunderlord', name: 'Thunderlord', description: 'Dual-Gen Tesla.', tier: 60, type: 'Tesla', barrels: [{offset:0,width:45,length:65,angle:0,delay:0},{offset:22,width:14,length:70,angle:0.05,delay:0},{offset:-22,width:14,length:70,angle:-0.05,delay:0}], stats: {damage:6,reload:2,range:450,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:5}, effect: 'SHOCK', skill: {type:'THUNDER_STORM',name:'Storm',cooldown:500,duration:15} },
  { id: 'barricade', name: 'Barricade', description: 'Trap Fortress.', tier: 60, type: 'Trap', barrels: [{offset:0,width:50,length:45,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:45,length:40,angle:0.3,delay:10,type:'Trapezoid' as const},{offset:0,width:45,length:40,angle:-0.3,delay:10,type:'Trapezoid' as const}], stats: {damage:50,reload:30,range:180,speed:3,spread:0,recoil:5,bulletSize:18,bulletCount:1}, skill: {type:'FORTIFY',name:'Iron Wall',cooldown:900,duration:300} },
  
  // --- NEW TIER 5 ADDITIONS ---
  { id: 'hive_mind', name: 'Hive Mind', description: 'Infection.', tier: 60, type: 'Trap', barrels: [{offset:0,width:45,length:60,angle:0,delay:0,type:'Injector' as const},{offset:30,width:20,length:50,angle:0.3,delay:5},{offset:-30,width:20,length:50,angle:-0.3,delay:5}], stats: {damage:15,reload:8,range:100,speed:7,spread:0.2,recoil:4,bulletSize:10,bulletCount:1}, effect: 'CORROSION', skill: {type:'RECALL',name:'Assimilate',cooldown:1200,duration:60} },
  { id: 'event_horizon_proto', name: 'Void Core', description: 'Gravity.', tier: 60, type: 'Ram', bodyType: 'Diamond', barrels: [{offset:0,width:60,length:50,angle:0,delay:0}], stats: {damage:8,reload:60,range:150,speed:0,spread:0,recoil:0,bulletSize:15,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Black Hole',cooldown:900,duration:120} },
  { id: 'poltergeist', name: 'Poltergeist', description: 'Glitch.', tier: 60, type: 'Bullet', bodyType: 'Star', barrels: [{offset:0,width:22,length:75,angle:0,delay:0},{offset:0,width:18,length:40,angle:Math.PI,delay:0}], stats: {damage:35,reload:40,range:130,speed:12,spread:0.1,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'TELEPORT',name:'Blink Step',cooldown:300,duration:30} },
  { id: 'valkyrie', name: 'Valkyrie', description: 'Assault.', tier: 60, type: 'Bullet', bodyType: 'Crescent', barrels: [{offset:0,width:22,length:65,angle:0,delay:0},{offset:18,width:16,length:50,angle:0.1,delay:0},{offset:-18,width:16,length:50,angle:-0.1,delay:0},{offset:35,width:12,length:40,angle:Math.PI-0.5,delay:0},{offset:-35,width:12,length:40,angle:Math.PI+0.5,delay:0}], stats: {damage:18,reload:12,range:70,speed:12,spread:0.1,recoil:8,bulletSize:8,bulletCount:1}, skill: {type:'DASH',name:'Afterburner',cooldown:200,duration:40} },
  { id: 'banshee_prime', name: 'Wailer', description: 'Sonic Scream.', tier: 60, type: 'Sonic', barrels: [{offset:0,width:60,length:60,angle:0,delay:0,type:'Dish' as const},{offset:25,width:30,length:40,angle:0.3,delay:0,type:'Dish' as const},{offset:-25,width:30,length:40,angle:-0.3,delay:0,type:'Dish' as const}], stats: {damage:20,reload:30,range:140,speed:7,spread:0.2,recoil:8,bulletSize:20,bulletCount:1}, skill: {type:'EMP',name:'Deafen',cooldown:600,duration:50} },
  { id: 'time_warper', name: 'Time Warper', description: 'Slows projectile.', tier: 60, type: 'Bullet', bodyType: 'Diamond', barrels: [{offset:0,width:30,length:70,angle:0,delay:0,type:'Construct' as const}], stats: {damage:30,reload:40,range:150,speed:8,spread:0,recoil:0,bulletSize:12,bulletCount:1}, skill: {type:'TIME_WARP',name:'Slow',cooldown:900,duration:120} },
  { id: 'bishop', name: 'Bishop', description: 'Healing Drone.', tier: 60, type: 'Healer', bodyType: 'Cross', barrels: [{offset:0,width:30,length:50,angle:0,delay:0,type:'Injector' as const}], stats: {damage:10,reload:50,range:0,speed:0,spread:0,recoil:0,bulletSize:10,bulletCount:4}, effect: 'HEAL', skill: {type:'RECALL',name:'Mend',cooldown:600,duration:60} }
];
