
import { WeaponSchema } from '../../types';

export const TIER_4_UNITS: WeaponSchema[] = [
  // --- BULLET SPAM ---
  { id: 'octo_tank', name: 'Octo Tank', description: '8 Directions.', tier: 45, type: 'Bullet', barrels: Array.from({length:8},(_,i)=>({offset:0,width:20,length:42,angle:i*Math.PI/4,delay:0})), stats: {damage:15,reload:30,range:55,speed:6,spread:0.05,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'BARRAGE',name:'Hurricane',cooldown:600,duration:180} },
  { id: 'penta_shot', name: 'Penta Shot', description: '5 Barrels arc.', tier: 45, type: 'Bullet', barrels: [{offset:0,width:22,length:42,angle:0,delay:0},{offset:12,width:20,length:38,angle:0.2,delay:5},{offset:-12,width:20,length:38,angle:-0.2,delay:5},{offset:22,width:18,length:32,angle:0.4,delay:10},{offset:-22,width:18,length:32,angle:-0.4,delay:10}], stats: {damage:14,reload:15,range:55,speed:7,spread:0.05,recoil:15,bulletSize:8,bulletCount:1}, skill: {type:'REPEL',name:'Recoil',cooldown:300,duration:60} },
  { id: 'spread_shot', name: 'Spread Shot', description: '11 Small barrels.', tier: 45, type: 'Bullet', barrels: [{offset:0,width:18,length:45,angle:0,delay:0},...Array.from({length:5},(_,i)=>({offset:0,width:10,length:38-i*2,angle:(i+1)*0.15,delay:i*2})),...Array.from({length:5},(_,i)=>({offset:0,width:10,length:38-i*2,angle:-(i+1)*0.15,delay:i*2}))], stats: {damage:8,reload:20,range:50,speed:7,spread:0.01,recoil:5,bulletSize:6,bulletCount:1}, skill: {type:'FOCUS',name:'Tighten',cooldown:600,duration:120} },
  { id: 'triplet', name: 'Triplet', description: 'Focused fire.', tier: 45, type: 'Bullet', barrels: [{offset:0,width:20,length:45,angle:0,delay:0},{offset:12,width:20,length:40,angle:0,delay:5},{offset:-12,width:20,length:40,angle:0,delay:5}], stats: {damage:16,reload:12,range:60,speed:7,spread:0.05,recoil:5,bulletSize:8,bulletCount:1}, skill: {type:'BARRAGE',name:'Overheat',cooldown:600,duration:60} },
  { id: 'auto_5', name: 'Auto-5', description: '5 Auto Turrets.', tier: 45, type: 'Bullet', barrels: Array.from({length:5},(_,i)=>({offset:0,width:14,length:24,angle:i*Math.PI*2/5,delay:i*5,type:'Auto' as const})), stats: {damage:10,reload:15,range:60,speed:8,spread:0.05,recoil:0,bulletSize:7,bulletCount:1}, skill: {type:'CHRONO_FIELD',name:'Grid',cooldown:1200,duration:180} },
  { id: 'triple_twin', name: 'Triple Twin', description: '3x Twin.', tier: 45, type: 'Bullet', barrels: [0, 2*Math.PI/3, 4*Math.PI/3].flatMap(a => [{offset:5,width:18,length:42,angle:a,delay:0},{offset:-5,width:18,length:42,angle:a,delay:10}]), stats: {damage:14,reload:18,range:60,speed:6,spread:0.05,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'BARRAGE',name:'Storm',cooldown:600,duration:180} },
  { id: 'hexa_tank', name: 'Hexa Tank', description: '6-Way.', tier: 45, type: 'Bullet', barrels: Array.from({length:6},(_,i)=>({offset:0,width:20,length:45,angle:i*Math.PI/3,delay:0})), stats: {damage:16,reload:25,range:60,speed:6,spread:0.05,recoil:0,bulletSize:9,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Hex Shield',cooldown:800,duration:120} },

  // --- SNIPER / ASSASSIN ---
  { id: 'ranger', name: 'Ranger', description: 'Max range.', tier: 45, type: 'Bullet', barrels: [{offset:0,width:30,length:110,angle:0,delay:0},{offset:0,width:36,length:40,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:100,reload:80,range:250,speed:20,spread:0,recoil:15,bulletSize:10,bulletCount:1}, skill: {type:'STEALTH',name:'Ghillie',cooldown:1200,duration:400} },
  { id: 'stalker', name: 'Stalker', description: 'Invisibility.', tier: 45, type: 'Bullet', bodyType: 'Trapezoid', barrels: [{offset:0,width:26,length:85,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:70,reload:60,range:160,speed:14,spread:0,recoil:5,bulletSize:9,bulletCount:1}, skill: {type:'STEALTH',name:'Vanish',cooldown:100,duration:999} },
  { id: 'predator', name: 'Predator', description: 'Zoom.', tier: 45, type: 'Bullet', barrels: [{offset:0,width:28,length:70,angle:0,delay:10},{offset:0,width:24,length:85,angle:0,delay:5},{offset:0,width:20,length:100,angle:0,delay:0}], stats: {damage:30,reload:60,range:180,speed:15,spread:0,recoil:8,bulletSize:8,bulletCount:1}, skill: {type:'FOCUS',name:'Zoom',cooldown:300,duration:999} },
  { id: 'dual_sniper', name: 'Dual Sniper', description: 'Twin long range.', tier: 45, type: 'Bullet', barrels: [{offset:8,width:20,length:80,angle:0,delay:0},{offset:-8,width:20,length:80,angle:0,delay:10}], stats: {damage:60,reload:65,range:180,speed:16,spread:0,recoil:12,bulletSize:9,bulletCount:1}, skill: {type:'FOCUS',name:'Double Tap',cooldown:600,duration:60} },

  // --- DRONE / MINION ---
  { id: 'overlord', name: 'Overlord', description: '4 Drones.', tier: 45, type: 'Drone', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:34,length:45,angle:a,delay:0,type:'Trapezoid' as const})), stats: {damage:30,reload:120,range:0,speed:0,spread:0,recoil:0,bulletSize:12,bulletCount:4}, skill: {type:'REPEL',name:'Claw',cooldown:120,duration:60} },
  { id: 'necromancer', name: 'Necromancer', description: 'Squares.', tier: 45, type: 'Necro', bodyType: 'Square', barrels: [{offset:0,width:45,length:45,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:45,length:45,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:15,reload:20,range:0,speed:0,spread:0,recoil:0,bulletSize:10,bulletCount:20}, skill: {type:'REPEL',name:'Sway',cooldown:120,duration:60} },
  { id: 'manager', name: 'Manager', description: 'Invisible.', tier: 45, type: 'Drone', barrels: [{offset:0,width:40,length:50,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:30,reload:80,range:0,speed:0,spread:0,recoil:0,bulletSize:12,bulletCount:4}, skill: {type:'STEALTH',name:'Hide',cooldown:300,duration:999} },
  { id: 'factory', name: 'Factory', description: 'Minions.', tier: 45, type: 'Minion', bodyType: 'Square', barrels: [{offset:0,width:40,length:50,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:10,reload:100,range:0,speed:0,spread:0,recoil:0,bulletSize:14,bulletCount:6}, skill: {type:'RECALL',name:'Regroup',cooldown:120,duration:60} },
  { id: 'carrier', name: 'Carrier', description: 'Swarm.', tier: 45, type: 'Swarm', barrels: [{offset:0,width:50,length:60,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:6,reload:20,range:80,speed:0,spread:0.5,recoil:0,bulletSize:5,bulletCount:12}, skill: {type:'MAGNET',name:'Hive Mind',cooldown:600,duration:180} },
  { id: 'auto_overseer', name: 'Auto Overseer', description: 'Drones + Auto.', tier: 45, type: 'Drone', barrels: [{offset:0,width:34,length:45,angle:Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:0,width:34,length:45,angle:-Math.PI/2,delay:0,type:'Trapezoid' as const},{offset:0,width:16,length:24,angle:0,delay:0,type:'Auto' as const}], stats: {damage:25,reload:100,range:0,speed:0,spread:0,recoil:0,bulletSize:10,bulletCount:2}, skill: {type:'REPEL',name:'Defend',cooldown:120,duration:60} },

  // --- TRAPPER / BUILDER ---
  { id: 'mega_trapper', name: 'Mega Trapper', description: 'Huge traps.', tier: 45, type: 'Trap', barrels: [{offset:0,width:60,length:55,angle:0,delay:0,type:'Trapezoid' as const}], stats: {damage:80,reload:80,range:300,speed:3,spread:0,recoil:10,bulletSize:22,bulletCount:1}, skill: {type:'FORTIFY',name:'Bastion',cooldown:900,duration:300} },
  { id: 'gunner_trapper', name: 'Gunner Trapper', description: 'Traps + Bullets.', tier: 45, type: 'Trap', barrels: [{offset:0,width:45,length:40,angle:Math.PI,delay:0,type:'Trapezoid' as const},{offset:12,width:12,length:50,angle:0,delay:0},{offset:-12,width:12,length:50,angle:0,delay:5}], stats: {damage:30,reload:10,range:60,speed:6,spread:0.1,recoil:5,bulletSize:12,bulletCount:1}, skill: {type:'FORTIFY',name:'Entrench',cooldown:900,duration:200} },
  { id: 'constructor', name: 'Constructor', description: 'Mega Walls.', tier: 45, type: 'Builder', bodyType: 'Square', barrels: [{offset:0,width:45,length:55,angle:0,delay:0,type:'Construct' as const},{offset:0,width:22,length:30,angle:Math.PI,delay:0}], stats: {damage:20,reload:60,range:150,speed:4,spread:0,recoil:15,bulletSize:18,bulletCount:1}, skill: {type:'CONSTRUCT_WALL',name:'Mega Wall',cooldown:1200,duration:600} },
  { id: 'engineer', name: 'Engineer', description: 'Trap + Drone.', tier: 45, type: 'Trap', barrels: [{offset:0,width:40,length:40,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:20,length:30,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:20,reload:50,range:120,speed:4,spread:0,recoil:0,bulletSize:12,bulletCount:1}, skill: {type:'FORTIFY',name:'Deploy',cooldown:900,duration:180} },

  // --- SHOTGUN / ROCKET ---
  { id: 'riot', name: 'Riot', description: 'Auto-Shotgun.', tier: 45, type: 'Shotgun', barrels: [{offset:0,width:40,length:55,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:34,length:65,angle:0,delay:0},{offset:20,width:10,length:50,angle:0,delay:0},{offset:-20,width:10,length:50,angle:0,delay:0},{offset:0,width:42,length:20,angle:0,delay:0,type:'Construct' as const}], stats: {damage:10,reload:25,range:60,speed:9,spread:0.4,recoil:12,bulletSize:7,bulletCount:6}, skill: {type:'BERSERK',name:'Full Auto',cooldown:450,duration:100} },
  { id: 'diffusion', name: 'Diffusion', description: 'Wide arc.', tier: 45, type: 'Shotgun', barrels: [{offset:0,width:35,length:50,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:35,length:50,angle:0.3,delay:0,type:'Trapezoid' as const},{offset:0,width:35,length:50,angle:-0.3,delay:0,type:'Trapezoid' as const}], stats: {damage:10,reload:40,range:50,speed:8,spread:0.2,recoil:10,bulletSize:6,bulletCount:3}, skill: {type:'BARRAGE',name:'Scatter',cooldown:500,duration:60} },
  { id: 'rocketeer', name: 'Rocketeer', description: 'Missile.', tier: 45, type: 'Launcher', barrels: [{offset:0,width:35,length:60,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:28,length:80,angle:0,delay:0},{offset:0,width:32,length:30,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:80,reload:50,range:120,speed:4,spread:0,recoil:10,bulletSize:12,bulletCount:1}, skill: {type:'ROCKET_JUMP',name:'Launch',cooldown:400,duration:20} },
  { id: 'artillery', name: 'Artillery', description: 'Lobbed shells.', tier: 45, type: 'Launcher', barrels: [{offset:0,width:45,length:50,angle:0,delay:0,type:'Construct' as const},{offset:0,width:30,length:75,angle:0,delay:0},{offset:0,width:36,length:10,angle:0,delay:0}], stats: {damage:100,reload:90,range:200,speed:12,spread:0.1,recoil:20,bulletSize:10,bulletCount:1}, skill: {type:'FORTIFY',name:'Anchor',cooldown:600,duration:120} },
  { id: 'skimmer', name: 'Skimmer', description: 'Spinning bullets.', tier: 45, type: 'Launcher', barrels: [{offset:0,width:24,length:65,angle:0,delay:0},{offset:0,width:40,length:45,angle:Math.PI,delay:0}], stats: {damage:30,reload:40,range:100,speed:6,spread:0,recoil:5,bulletSize:15,bulletCount:2}, skill: {type:'PHANTOM_STEP',name:'Drift',cooldown:300,duration:30} },
  
  // REBALANCED CLUSTER LAUNCHER (SINGLE BARREL, REALISTIC PHYSICS)
  { 
    id: 'cluster_launcher', name: 'Cluster Cannon', description: 'Splitting Bombs.', tier: 45, type: 'Launcher', bodyType: 'Trapezoid',
    barrels: [
        // JUST ONE MAIN BARREL FOR PHYSICS
        {offset:0, width:40, length:55, angle:0, delay:0, type:'Trapezoid' as const}
    ],
    // High damage, High Recoil (25)
    stats: {damage: 45, reload: 65, range: 160, speed: 8, spread: 0.05, recoil: 25, bulletSize: 14, bulletCount: 1},
    skill: {type: 'BARRAGE', name: 'Cluster Barrage', cooldown: 700, duration: 60}
  },

  // --- RAMMERS / SPEEDSTERS ---
  { id: 'landmine', name: 'Landmine', description: 'Invisible Ram.', tier: 45, type: 'Ram', bodyType: 'Hexagon', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'STEALTH',name:'Burrow',cooldown:120,duration:999} },
  { id: 'booster', name: 'Booster', description: 'Maximum speed.', tier: 45, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:22,length:50,angle:0,delay:0},{offset:0,width:20,length:38,angle:2.5,delay:0},{offset:0,width:20,length:38,angle:-2.5,delay:0},{offset:0,width:16,length:30,angle:2.3,delay:0},{offset:0,width:16,length:30,angle:-2.3,delay:0}], stats: {damage:15,reload:15,range:50,speed:7,spread:0.1,recoil:12,bulletSize:9,bulletCount:1}, skill: {type:'DASH',name:'Turbo',cooldown:200,duration:30} },
  { id: 'fighter', name: 'Fighter', description: 'Side guns.', tier: 45, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:22,length:50,angle:0,delay:0},{offset:0,width:20,length:38,angle:2.5,delay:0},{offset:0,width:20,length:38,angle:-2.5,delay:0},{offset:0,width:18,length:40,angle:Math.PI/2,delay:0},{offset:0,width:18,length:40,angle:-Math.PI/2,delay:0}], stats: {damage:15,reload:15,range:50,speed:7,spread:0.1,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'DASH',name:'Maneuver',cooldown:300,duration:30} },
  { id: 'bomber', name: 'Bomber', description: 'Speed Ram.', tier: 45, type: 'Ram', bodyType: 'Tri', barrels: [{offset:0,width:16,length:30,angle:Math.PI,delay:0}], stats: {damage:0,reload:20,range:0,speed:8,spread:0,recoil:15,bulletSize:0,bulletCount:0}, skill: {type:'BERSERK',name:'Kamikaze',cooldown:400,duration:100} },
  
  // --- SPECIAL RAMMERS (Requested) ---
  { 
    id: 'bulldozer', name: 'Bulldozer', description: 'Armored plow.', tier: 45, type: 'Ram', bodyType: 'Trapezoid',
    barrels: [{offset: 25, width: 22, length: 45, angle: Math.PI, delay: 0}, {offset: -25, width: 22, length: 45, angle: Math.PI, delay: 0}], 
    stats: {damage: 8, reload: 4, range: 40, speed: 6, spread: 0.1, recoil: 18, bulletSize: 10, bulletCount: 1}, 
    skill: {type: 'SHIELD', name: 'Iron Plow', cooldown: 600, duration: 200} 
  },
  {
    id: 'buzzsaw', name: 'Buzzsaw', description: 'Spinning blade.', tier: 45, type: 'Ram', bodyType: 'Saw',
    barrels: [{offset: 15, width: 12, length: 25, angle: Math.PI, delay: 0}, {offset: -15, width: 12, length: 25, angle: Math.PI, delay: 0}], // Rear exhausts
    stats: {damage: 10, reload: 0, range: 0, speed: 7, spread: 0, recoil: 5, bulletSize: 0, bulletCount: 0},
    skill: {type: 'OVERCLOCK', name: 'Rev Up', cooldown: 450, duration: 90}
  },
  {
    id: 'briar', name: 'Briar', description: 'Barbed spikes.', tier: 45, type: 'Ram', bodyType: 'Spike',
    barrels: Array.from({length: 8}, (_, i) => ({offset: 0, width: 8, length: 35, angle: i * Math.PI / 4, delay: 0, type: 'Spike' as const})),
    stats: {damage: 8, reload: 0, range: 0, speed: 5, spread: 0, recoil: 0, bulletSize: 0, bulletCount: 0},
    skill: {type: 'NANO_ARMOR', name: 'Thorns', cooldown: 600, duration: 180}
  },

  // --- EXPERIMENTAL ---
  { id: 'ballista', name: 'Ballista', description: 'Charge shot.', tier: 45, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:34,length:100,angle:0,delay:0},{offset:0,width:45,length:70,angle:0,delay:0}], stats: {damage:100,reload:80,range:220,speed:25,spread:0,recoil:30,bulletSize:10,bulletCount:1}, skill: {type:'FOCUS',name:'Siege',cooldown:600,duration:180} },
  { id: 'paladin', name: 'Paladin', description: 'Shield Healer.', tier: 45, type: 'Healer', bodyType: 'Cross', barrels: [{offset:0,width:26,length:55,angle:0,delay:0,type:'Injector' as const},{offset:14,width:14,length:35,angle:0.5,delay:0,type:'Injector' as const},{offset:-14,width:14,length:35,angle:-0.5,delay:0,type:'Injector' as const}], stats: {damage:8,reload:10,range:100,speed:10,spread:0.2,recoil:3,bulletSize:9,bulletCount:1}, effect: 'HEAL', skill: {type:'SHIELD',name:'Sanctuary',cooldown:900,duration:200} },
  { id: 'tesla', name: 'Tesla', description: 'Chain Lightning.', tier: 45, type: 'Tesla', barrels: [{offset:0,width:36,length:55,angle:0,delay:0},{offset:14,width:12,length:60,angle:0.1,delay:0},{offset:-14,width:12,length:60,angle:-0.1,delay:0}], stats: {damage:4,reload:2,range:350,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:2}, effect: 'SHOCK', skill: {type:'EMP',name:'Static',cooldown:600,duration:30} },
  { id: 'plague', name: 'Plague', description: 'Viral.', tier: 45, type: 'Trap', barrels: [{offset:0,width:35,length:50,angle:0,delay:0,type:'Injector' as const},{offset:20,width:15,length:40,angle:0.4,delay:0},{offset:-20,width:15,length:40,angle:-0.4,delay:0}], stats: {damage:12,reload:10,range:90,speed:6,spread:0.4,recoil:3,bulletSize:9,bulletCount:1}, effect: 'CORROSION', skill: {type:'GRAVITY_WELL',name:'Outbreak',cooldown:900,duration:180} },
  { id: 'singularity', name: 'Singularity', description: 'Mini hole.', tier: 45, type: 'Ram', bodyType: 'Crescent', barrels: [{offset:0,width:40,length:40,angle:0,delay:0}], stats: {damage:5,reload:60,range:100,speed:0,spread:0,recoil:0,bulletSize:12,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Collapse',cooldown:600,duration:60} },
  { id: 'blizzard', name: 'Blizzard', description: 'Cone cold.', tier: 45, type: 'Flamethrower', barrels: [{offset:0,width:40,length:60,angle:0,delay:0,type:'Construct' as const},{offset:0,width:20,length:50,angle:0,delay:0}], stats: {damage:7,reload:3,range:70,speed:10,spread:0.3,recoil:4,bulletSize:10,bulletCount:1}, effect: 'FREEZE', skill: {type:'CHRONO_FIELD',name:'Deep Freeze',cooldown:900,duration:120} },
  { id: 'spectre', name: 'Spectre', description: 'Phase.', tier: 45, type: 'Bullet', bodyType: 'Diamond', barrels: [{offset:0,width:24,length:65,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:10,length:80,angle:0,delay:0}], stats: {damage:40,reload:50,range:120,speed:15,spread:0,recoil:2,bulletSize:9,bulletCount:1}, skill: {type:'PHANTOM_STEP',name:'Ghost',cooldown:400,duration:60} },
  { id: 'banshee', name: 'Banshee', description: 'Sonic.', tier: 45, type: 'Sonic', barrels: [{offset:0,width:50,length:50,angle:0,delay:0,type:'Dish' as const},{offset:0,width:30,length:30,angle:Math.PI,delay:0,type:'Dish' as const}], stats: {damage:18,reload:30,range:120,speed:7,spread:0,recoil:5,bulletSize:18,bulletCount:1}, skill: {type:'EMP',name:'Scream',cooldown:500,duration:40} },
  { id: 'prism_v2', name: 'Refractor', description: 'Split shot.', tier: 45, type: 'Bullet', bodyType: 'Tri', barrels: [{offset:0,width:24,length:55,angle:0,delay:0},{offset:15,width:12,length:45,angle:0.3,delay:0},{offset:-15,width:12,length:45,angle:-0.3,delay:0},{offset:30,width:10,length:35,angle:0.6,delay:0},{offset:-30,width:10,length:35,angle:-0.6,delay:0}], stats: {damage:10,reload:25,range:70,speed:8,spread:0.1,recoil:3,bulletSize:7,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Prism Guard',cooldown:600,duration:120} },
  { id: 'inquisitor', name: 'Inquisitor', description: 'Laser + Drone.', tier: 45, type: 'Laser', barrels: [{offset:0,width:20,length:75,angle:0,delay:0},{offset:0,width:30,length:40,angle:Math.PI,delay:0,type:'Trapezoid' as const}], stats: {damage:25,reload:40,range:140,speed:20,spread:0,recoil:2,bulletSize:6,bulletCount:1}, skill: {type:'FOCUS',name:'Interrogate',cooldown:500,duration:100} },
  { id: 'sidewinder', name: 'Sidewinder', description: 'Curved shots.', tier: 45, type: 'Bullet', barrels: [{offset:10,width:18,length:50,angle:0,delay:0},{offset:-10,width:18,length:50,angle:0,delay:5}], stats: {damage:15,reload:20,range:90,speed:8,spread:0.2,recoil:3,bulletSize:8,bulletCount:1}, skill: {type:'DASH',name:'Weave',cooldown:300,duration:30} }
];
