
import { WeaponSchema } from '../../types';

// --- TIER 6 (LVL 75) - LEGENDARY ---
export const TIER_6_UNITS: WeaponSchema[] = [
  { id: 'tempest', name: 'Tempest', description: 'Spinning shotgun.', tier: 75, type: 'Shotgun', barrels: [0, 2*Math.PI/3, 4*Math.PI/3].map(a=>({offset:0,width:35,length:55,angle:a,delay:0,type:'Trapezoid' as const})), stats: {damage:12,reload:20,range:60,speed:8,spread:0.3,recoil:0,bulletSize:6,bulletCount:3}, skill: {type:'BARRAGE',name:'Death Blossom',cooldown:600,duration:180} },
  { id: 'meteor', name: 'Meteor', description: 'Nuke.', tier: 75, type: 'Launcher', barrels: [{offset:0,width:50,length:70,angle:0,delay:0,type:'Construct' as const},{offset:0,width:40,length:85,angle:0,delay:0}], stats: {damage:150,reload:80,range:200,speed:3,spread:0,recoil:30,bulletSize:16,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Impact',cooldown:900,duration:60} },
  { id: 'hurricane', name: 'Hurricane', description: '12-Barrel.', tier: 75, type: 'Bullet', barrels: Array.from({length:12},(_,i)=>({offset:0,width:18,length:50,angle:i*Math.PI*2/12,delay:0})), stats: {damage:14,reload:25,range:60,speed:6,spread:0.1,recoil:0,bulletSize:8,bulletCount:1}, skill: {type:'BARRAGE',name:'Typhoon',cooldown:600,duration:300} },
  { id: 'obelisk', name: 'Obelisk', description: 'Immovable.', tier: 75, type: 'Builder', bodyType: 'Octagon', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:65,length:65,angle:a,delay:0,type:'Construct' as const})), stats: {damage:50,reload:120,range:300,speed:0,spread:0,recoil:0,bulletSize:25,bulletCount:4}, skill: {type:'CONSTRUCT_WALL',name:'Fortress',cooldown:2400,duration:1200} },
  { id: 'arbitrator', name: 'Arbitrator', description: 'Heavy Laser.', tier: 75, type: 'Laser', barrels: [{offset:0,width:35,length:105,angle:0,delay:0},{offset:0,width:14,length:28,angle:Math.PI,delay:0,type:'Auto' as const}], stats: {damage:50,reload:50,range:200,speed:25,spread:0,recoil:10,bulletSize:7,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Refractor',cooldown:1200,duration:300} },
  { id: 'leviathan', name: 'Leviathan', description: 'Triple Streamliner.', tier: 75, type: 'Bullet', barrels: [{offset:0,width:30,length:90,angle:0,delay:0},{offset:0,width:25,length:80,angle:0,delay:0},{offset:0,width:20,length:70,angle:0,delay:0},{offset:0,width:20,length:70,angle:0.2,delay:5},{offset:0,width:15,length:60,angle:0.2,delay:5},{offset:0,width:20,length:70,angle:-0.2,delay:5},{offset:0,width:15,length:60,angle:-0.2,delay:5}], stats: {damage:7,reload:10,range:90,speed:9,spread:0.05,recoil:5,bulletSize:6,bulletCount:1}, skill: {type:'FOCUS',name:'Obliterate',cooldown:900,duration:120} },
  { id: 'vortex', name: 'Vortex', description: 'Gravity Ram.', tier: 75, type: 'Ram', bodyType: 'Star', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'GRAVITY_WELL',name:'Singularity',cooldown:900,duration:200} },
  { id: 'omni_trapper', name: 'Fortress', description: 'Omni-Traps.', tier: 75, type: 'Trap', barrels: [...[0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:35,length:40,angle:a,delay:0,type:'Trapezoid' as const})),{offset:0,width:16,length:28,angle:0,delay:0,type:'Auto' as const}], stats: {damage:45,reload:50,range:200,speed:4,spread:0,recoil:0,bulletSize:14,bulletCount:1}, skill: {type:'FORTIFY',name:'Lockdown',cooldown:1200,duration:360} },
  { id: 'seraph', name: 'Seraph', description: 'Healing Angel.', tier: 75, type: 'Healer', bodyType: 'Cross', barrels: [{offset:0,width:34,length:65,angle:0,delay:0,type:'Injector' as const},{offset:0,width:12,length:85,angle:0,delay:0},{offset:22,width:18,length:45,angle:0.4,delay:0,type:'Injector' as const},{offset:-22,width:18,length:45,angle:-0.4,delay:0,type:'Injector' as const}], stats: {damage:12,reload:8,range:120,speed:12,spread:0.1,recoil:5,bulletSize:10,bulletCount:1}, effect: 'HEAL', skill: {type:'NANO_ARMOR',name:'Divine',cooldown:1200,duration:300} },
  { id: 'quasar', name: 'Quasar', description: 'Massive Beam.', tier: 75, type: 'Laser', barrels: [{offset:0,width:30,length:100,angle:0,delay:0},{offset:0,width:45,length:65,angle:0,delay:0}], stats: {damage:100,reload:60,range:250,speed:30,spread:0,recoil:20,bulletSize:10,bulletCount:1}, skill: {type:'ORBITAL_BEAM',name:'Strike',cooldown:1500,duration:80} },
  { id: 'glitch_lord', name: 'Glitch Lord', description: 'Unstable.', tier: 75, type: 'Bullet', bodyType: 'Diamond', barrels: [{offset:0,width:25,length:80,angle:0,delay:0},{offset:20,width:10,length:60,angle:0.2,delay:0},{offset:-20,width:10,length:60,angle:-0.2,delay:0}], stats: {damage:40,reload:35,range:140,speed:14,spread:0.1,recoil:5,bulletSize:8,bulletCount:1}, skill: {type:'TIME_WARP',name:'Lag Spike',cooldown:600,duration:60} },
  { id: 'overmind', name: 'Overmind', description: 'Massive swarm.', tier: 75, type: 'Swarm', bodyType: 'Octagon', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:45,length:50,angle:a,delay:0,type:'Trapezoid' as const})), stats: {damage:6,reload:15,range:100,speed:0,spread:0.5,recoil:0,bulletSize:5,bulletCount:40}, skill: {type:'RECALL',name:'Legion',cooldown:900,duration:120} },
  { id: 'scythe', name: 'Scythe', description: 'Sonic Blade.', tier: 75, type: 'Sonic', bodyType: 'Crescent', barrels: [{offset:0,width:70,length:70,angle:0,delay:0,type:'Dish' as const},{offset:0,width:20,length:40,angle:Math.PI,delay:0}], stats: {damage:25,reload:25,range:150,speed:8,spread:0,recoil:10,bulletSize:25,bulletCount:1}, skill: {type:'PHANTOM_STEP',name:'Reap',cooldown:400,duration:40} },
  { id: 'volcano', name: 'Volcano', description: 'Erupt.', tier: 75, type: 'Flamethrower', barrels: Array.from({length:6},(_,i)=>({offset:0,width:30,length:60,angle:i*Math.PI/3,delay:i*2,type:'Trapezoid' as const})), stats: {damage:8,reload:2,range:70,speed:10,spread:0.4,recoil:0,bulletSize:12,bulletCount:1}, effect: 'BURN', skill: {type:'GRAVITY_WELL',name:'Eruption',cooldown:900,duration:180} }
];

// --- TIER 7 (LVL 90) - DISASTER ---
export const TIER_7_UNITS: WeaponSchema[] = [
  { id: 'juggernaut', name: 'Juggernaut', description: 'Rocket Fortress.', tier: 90, type: 'Launcher', bodyType: 'Octagon', barrels: [{offset:0,width:40,length:60,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:30,length:50,angle:0.5,delay:10,type:'Trapezoid' as const},{offset:0,width:30,length:50,angle:-0.5,delay:10,type:'Trapezoid' as const},{offset:0,width:24,length:30,angle:Math.PI,delay:0,type:'Auto' as const}], stats: {damage:60,reload:25,range:180,speed:5,spread:0.1,recoil:5,bulletSize:10,bulletCount:1}, skill: {type:'NANO_ARMOR',name:'Plating',cooldown:900,duration:300} },
  { id: 'devastator', name: 'Devastator', description: 'Ult Shotgun.', tier: 90, type: 'Shotgun', barrels: [{offset:0,width:60,length:70,angle:0,delay:0,type:'Construct' as const},{offset:0,width:50,length:80,angle:0,delay:0},{offset:35,width:15,length:60,angle:0.1,delay:0},{offset:-35,width:15,length:60,angle:-0.1,delay:0},{offset:20,width:10,length:50,angle:0,delay:5},{offset:-20,width:10,length:50,angle:0,delay:5}], stats: {damage:18,reload:50,range:80,speed:12,spread:0.35,recoil:40,bulletSize:8,bulletCount:12}, skill: {type:'BERSERK',name:'Rampage',cooldown:600,duration:120} },
  { id: 'nova', name: 'Nova', description: '8 Destroyer.', tier: 90, type: 'Bullet', barrels: Array.from({length:8},(_,i)=>({offset:0,width:50,length:55,angle:i*Math.PI*2/8,delay:0})), stats: {damage:80,reload:150,range:60,speed:4,spread:0,recoil:0,bulletSize:9,bulletCount:1}, skill: {type:'REPEL',name:'Supernova',cooldown:900,duration:60} },
  { id: 'mothership', name: 'Mothership', description: '16 Drones.', tier: 90, type: 'Drone', bodyType: 'Octagon', barrels: Array.from({length:8},(_,i)=>({offset:0,width:40,length:55,angle:i*Math.PI*2/8,delay:i*5,type:'Trapezoid' as const})), stats: {damage:25,reload:40,range:0,speed:0,spread:0,recoil:0,bulletSize:10,bulletCount:16}, skill: {type:'REPEL',name:'All Range',cooldown:600,duration:100} },
  { id: 'lich', name: 'The Lich', description: 'Infinite.', tier: 90, type: 'Necro', bodyType: 'Square', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:55,length:55,angle:a,delay:0,type:'Trapezoid' as const})), stats: {damage:20,reload:10,range:0,speed:0,spread:0,recoil:0,bulletSize:12,bulletCount:40}, skill: {type:'REPEL',name:'Legion',cooldown:300,duration:120} },
  { id: 'ragnarok', name: 'Ragnarok', description: 'Flaming Saw.', tier: 90, type: 'Ram', bodyType: 'Saw', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'BERSERK',name:'Ragnarok',cooldown:600,duration:240} },
  { id: 'titan', name: 'Titan', description: 'Immortal.', tier: 90, type: 'Ram', bodyType: 'Hexagon', barrels: [], stats: {damage:0,reload:0,range:0,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:0}, skill: {type:'NANO_ARMOR',name:'Titanium',cooldown:900,duration:400} },
  { id: 'helix', name: 'Helix', description: 'DNA.', tier: 90, type: 'Bullet', barrels: [{offset:22,width:18,length:65,angle:0,delay:0},{offset:-22,width:18,length:65,angle:0,delay:0},{offset:0,width:28,length:55,angle:0,delay:5}], stats: {damage:30,reload:15,range:90,speed:9,spread:0,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'TIME_WARP',name:'Splice',cooldown:1200,duration:150} },
  { id: 'black_hole', name: 'Singularity', description: 'Void Pull.', tier: 90, type: 'Bullet', barrels: [{offset:0,width:70,length:45,angle:0,delay:0},{offset:65,width:12,length:55,angle:0.2,delay:0},{offset:-65,width:12,length:55,angle:-0.2,delay:0}], stats: {damage:50,reload:10,range:50,speed:8,spread:0.2,recoil:5,bulletSize:8,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Horizon',cooldown:900,duration:240} },
  { id: 'solar', name: 'Solar', description: 'Sun beams.', tier: 90, type: 'Laser', bodyType: 'Star', barrels: [0, Math.PI/2, Math.PI, -Math.PI/2].map(a => ({offset:0,width:30,length:80,angle:a,delay:0})), stats: {damage:60,reload:30,range:200,speed:30,spread:0,recoil:5,bulletSize:8,bulletCount:1}, skill: {type:'ORBITAL_BEAM',name:'Solar Flare',cooldown:900,duration:100} },
  { id: 'zeus', name: 'Zeus', description: 'Lightning God.', tier: 90, type: 'Tesla', barrels: [{offset:0,width:50,length:80,angle:0,delay:0},{offset:30,width:15,length:70,angle:0.2,delay:0},{offset:-30,width:15,length:70,angle:-0.2,delay:0}], stats: {damage:8,reload:1,range:500,speed:0,spread:0,recoil:0,bulletSize:0,bulletCount:10}, effect: 'SHOCK', skill: {type:'THUNDER_STORM',name:'Wrath',cooldown:600,duration:60} },
  { id: 'siren', name: 'Siren', description: 'Sound Nuke.', tier: 90, type: 'Sonic', bodyType: 'Crescent', barrels: [{offset:0,width:90,length:90,angle:0,delay:0,type:'Dish' as const}], stats: {damage:40,reload:60,range:200,speed:10,spread:0,recoil:20,bulletSize:30,bulletCount:1}, skill: {type:'EMP',name:'Opera',cooldown:900,duration:100} },
  { id: 'ice_age', name: 'Ice Age', description: 'Global Freeze.', tier: 90, type: 'Flamethrower', barrels: Array.from({length:8},(_,i)=>({offset:0,width:40,length:70,angle:i*Math.PI*2/8,delay:i*2,type:'Trapezoid' as const})), stats: {damage:12,reload:2,range:80,speed:12,spread:0.3,recoil:0,bulletSize:16,bulletCount:1}, effect: 'FREEZE', skill: {type:'CHRONO_FIELD',name:'Absolute Zero',cooldown:1200,duration:300} }
];

// --- TIER 8 (LVL 100) - THE GODS ---
export const TIER_8_UNITS: WeaponSchema[] = [
  { id: 'apocalypse', name: 'Apocalypse', description: 'Nuclear End.', tier: 100, type: 'Launcher', bodyType: 'Diamond', barrels: [{offset:0,width:60,length:90,angle:0,delay:0,type:'Construct' as const},{offset:0,width:50,length:100,angle:0,delay:0},{offset:40,width:25,length:70,angle:0.2,delay:20,type:'Trapezoid' as const},{offset:-40,width:25,length:70,angle:-0.2,delay:20,type:'Trapezoid' as const}], stats: {damage:250,reload:120,range:300,speed:3,spread:0,recoil:50,bulletSize:20,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Fallout',cooldown:1200,duration:400} },
  { id: 'the_sovereign', name: 'The Sovereign', description: 'Hybrid.', tier: 100, type: 'Drone', bodyType: 'Spike', barrels: [{offset:0,width:45,length:85,angle:0,delay:0},{offset:0,width:35,length:95,angle:0,delay:0},{offset:0,width:12,length:115,angle:0,delay:0},{offset:38,width:18,length:35,angle:0.5,delay:0,type:'Auto' as const},{offset:-38,width:18,length:35,angle:-0.5,delay:0,type:'Auto' as const},{offset:24,width:28,length:45,angle:Math.PI-0.5,delay:0,type:'Trapezoid' as const},{offset:-24,width:28,length:45,angle:Math.PI+0.5,delay:0,type:'Trapezoid' as const},{offset:0,width:24,length:35,angle:Math.PI,delay:0}], stats: {damage:250,reload:40,range:130,speed:13,spread:0,recoil:40,bulletSize:25,bulletCount:6}, skill: {type:'TIME_WARP',name:'Omnipresence',cooldown:1800,duration:300} },
  { id: 'event_horizon', name: 'Event Horizon', description: 'Omni.', tier: 100, type: 'Bullet', barrels: [...[0, Math.PI/3, 2*Math.PI/3, Math.PI, 4*Math.PI/3, 5*Math.PI/3].map(a => ({offset:0,width:55,length:65,angle:a,delay:0})),{offset:0,width:14,length:24,angle:0,delay:0,type:'Auto' as const}], stats: {damage:150,reload:20,range:90,speed:6,spread:0,recoil:10,bulletSize:9,bulletCount:1}, skill: {type:'GRAVITY_WELL',name:'Black Hole',cooldown:900,duration:300} },
  { id: 'omega_zero', name: 'Omega Zero', description: 'Perfect.', tier: 100, type: 'Trap', barrels: [{offset:0,width:65,length:45,angle:0,delay:0,type:'Trapezoid' as const},{offset:0,width:45,length:85,angle:0,delay:0},{offset:42,width:18,length:65,angle:0.2,delay:0},{offset:-42,width:18,length:65,angle:-0.2,delay:0},{offset:0,width:22,length:35,angle:Math.PI,delay:0,type:'Auto' as const}], stats: {damage:100,reload:30,range:150,speed:10,spread:0.1,recoil:20,bulletSize:12,bulletCount:1}, skill: {type:'MIRROR_PRISM',name:'Mirror',cooldown:1200,duration:600} },
  { id: 'archon', name: 'Archon', description: 'Architect.', tier: 100, type: 'Builder', bodyType: 'Octagon', barrels: [{offset:0,width:90,length:85,angle:0,delay:0,type:'Construct' as const},{offset:0,width:45,length:130,angle:Math.PI/4,delay:0},{offset:0,width:45,length:130,angle:-Math.PI/4,delay:0},{offset:0,width:45,length:130,angle:3*Math.PI/4,delay:0},{offset:0,width:45,length:130,angle:-3*Math.PI/4,delay:0}], stats: {damage:80,reload:150,range:400,speed:2,spread:0,recoil:25,bulletSize:10,bulletCount:1}, skill: {type:'CONSTRUCT_WALL',name:'Weave',cooldown:3000,duration:2000} },
  { id: 'hypernova', name: 'Hypernova', description: 'Starborn.', tier: 100, type: 'Laser', bodyType: 'Star', barrels: Array.from({length:5},(_,i)=>({offset:0,width:40,length:120,angle:i*Math.PI*2/5,delay:0})), stats: {damage:150,reload:40,range:300,speed:40,spread:0,recoil:10,bulletSize:15,bulletCount:1}, skill: {type:'ORBITAL_BEAM',name:'Gamma Burst',cooldown:1500,duration:100} },
  { id: 'pandemic_lord', name: 'Pandemic', description: 'Plague God.', tier: 100, type: 'Trap', barrels: [{offset:0,width:60,length:80,angle:0,delay:0,type:'Injector' as const},{offset:40,width:20,length:60,angle:0.3,delay:0},{offset:-40,width:20,length:60,angle:-0.3,delay:0}], stats: {damage:40,reload:10,range:150,speed:8,spread:0.5,recoil:10,bulletSize:12,bulletCount:1}, effect: 'CORROSION', skill: {type:'GRAVITY_WELL',name:'Extinction',cooldown:1800,duration:400} },
  { id: 'resonance', name: 'Resonance', description: 'Sound God.', tier: 100, type: 'Sonic', bodyType: 'Crescent', barrels: Array.from({length:3},(_,i)=>({offset:0,width:100,length:80,angle:i*Math.PI*2/3,delay:0,type:'Dish' as const})), stats: {damage:60,reload:40,range:300,speed:12,spread:0,recoil:30,bulletSize:40,bulletCount:1}, skill: {type:'EMP',name:'Shatter',cooldown:1000,duration:200} }
];
